In [24]:
import pandas as pd
base = 'archive/'
data = pd.read_csv(base + 'mental_health_diagnosis_treatment_.csv', sep=',')
data.describe()

,Patient ID,Age,Symptom Severity (1-10),Mood Score (1-10),Sleep Quality (1-10),Physical Activity (hrs/week),Treatment Duration (weeks),Stress Level (1-10),Treatment Progress (1-10),Adherence to Treatment (%)
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000
mean,250.500000,38.708000,7.478000,5.482000,6.472000,5.216000,12.110000,7.542000,7.436000,75.45400
std,144.481833,12.712433,1.706265,1.707486,1.668167,2.829374,2.440864,1.709409,1.725067,9.08697
min,1.000000,18.000000,5.000000,3.000000,4.000000,1.000000,8.000000,5.000000,5.000000,60.00000
25%,125.750000,28.000000,6.000000,4.000000,5.000000,3.000000,10.000000,6.000000,6.000000,67.00000
50%,250.500000,38.000000,8.000000,5.000000,6.000000,5.000000,12.000000,8.000000,7.000000,76.00000
75%,375.250000,50.000000,9.000000,7.000000,8.000000,8.000000,14.000000,9.000000,9.000000,84.00000
max,500.000000,60.000000,10.000000,8.000000,9.000000,10.000000,16.000000,10.000000,10.000000,90.00000

In [25]:
data.describe()

,Patient ID,Age,Symptom Severity (1-10),Mood Score (1-10),Sleep Quality (1-10),Physical Activity (hrs/week),Treatment Duration (weeks),Stress Level (1-10),Treatment Progress (1-10),Adherence to Treatment (%)
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000
mean,250.500000,38.708000,7.478000,5.482000,6.472000,5.216000,12.110000,7.542000,7.436000,75.45400
std,144.481833,12.712433,1.706265,1.707486,1.668167,2.829374,2.440864,1.709409,1.725067,9.08697
min,1.000000,18.000000,5.000000,3.000000,4.000000,1.000000,8.000000,5.000000,5.000000,60.00000
25%,125.750000,28.000000,6.000000,4.000000,5.000000,3.000000,10.000000,6.000000,6.000000,67.00000
50%,250.500000,38.000000,8.000000,5.000000,6.000000,5.000000,12.000000,8.000000,7.000000,76.00000
75%,375.250000,50.000000,9.000000,7.000000,8.000000,8.000000,14.000000,9.000000,9.000000,84.00000
max,500.000000,60.000000,10.000000,8.000000,9.000000,10.000000,16.000000,10.000000,10.000000,90.00000

In [ ]:
mh_features=['Patient ID', 'Diagnosis']
X=data[mh_features]
print(data.dtypes) 
X.head

Patient ID                       int64
Age                              int64
Gender                          object
Diagnosis                       object
Symptom Severity (1-10)          int64
Mood Score (1-10)                int64
Sleep Quality (1-10)             int64
Physical Activity (hrs/week)     int64
Medication                      object
Therapy Type                    object
Treatment Start Date            object
Treatment Duration (weeks)       int64
Stress Level (1-10)              int64
Outcome                         object
Treatment Progress (1-10)        int64
AI-Detected Emotional State     object
Adherence to Treatment (%)       int64
dtype: object

        Patient ID            Diagnosis
count   500.000000                  500
unique         NaN                    4
top            NaN  Generalized Anxiety
freq           NaN                  135
mean    250.500000                  NaN
std     144.481833                  NaN
min       1.000000                  NaN
25%     125.750000                  NaN
50%     250.500000                  NaN
75%     375.250000                  NaN
max     500.000000                  NaN